FROM golang:alpine

WORKDIR /src
COPY go.mod go.sum ./

RUN go mod download

COPY ./app/job-service ./app/job-service
COPY ./pkg ./pkg

RUN go install github.com/cosmtrek/air@latest

CMD air --build.cmd "go build -o /tmp/app ./app/job-service/main.go" --build.bin "/tmp/app"