FROM golang:alpine

WORKDIR /src
COPY go.mod go.sum ./

RUN go mod download

COPY ./app/crawler-manager ./app/crawler-manager
COPY ./pkg ./pkg

RUN go install github.com/cosmtrek/air@latest

CMD air --build.cmd "go build -o /tmp/app ./app/crawler-manager/main.go" --build.bin "/tmp/app"
